CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, email TEXT UNIQUE NOT NULL, display_name TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'user', email_verified BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversations (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY, conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE, role TEXT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS provider TEXT NOT NULL DEFAULT '';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS model TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS ai_usage (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL, provider TEXT NOT NULL, model TEXT NOT NULL, input_chars INTEGER NOT NULL DEFAULT 0, output_chars INTEGER NOT NULL DEFAULT 0, estimated_cost_micros BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_usage_user_created_idx ON ai_usage(user_id, created_at);
CREATE TABLE IF NOT EXISTS documents (id BIGSERIAL PRIMARY KEY, owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, content TEXT NOT NULL, search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('french', title || ' ' || content)) STORED);
CREATE INDEX IF NOT EXISTS documents_search_idx ON documents USING GIN(search_vector);
CREATE TABLE IF NOT EXISTS public_search_documents (id BIGSERIAL PRIMARY KEY, url TEXT UNIQUE NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'crawler', crawled_at TIMESTAMPTZ NOT NULL DEFAULT now(), search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('french', title || ' ' || content)) STORED);
CREATE INDEX IF NOT EXISTS public_search_documents_search_idx ON public_search_documents USING GIN(search_vector);
ALTER TABLE public_search_documents ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE public_search_documents ADD COLUMN IF NOT EXISTS canonical_url TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS search_crawl_queue (url TEXT PRIMARY KEY, status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','crawling','complete','failed')), attempts INTEGER NOT NULL DEFAULT 0, requested_at TIMESTAMPTZ NOT NULL DEFAULT now(), started_at TIMESTAMPTZ, crawled_at TIMESTAMPTZ, last_error TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS search_crawl_queue_pending_idx ON search_crawl_queue(status, requested_at);
CREATE TABLE IF NOT EXISTS crawler_hosts (host TEXT PRIMARY KEY, crawl_delay_seconds INTEGER NOT NULL DEFAULT 5, next_allowed_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_error TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS permissions (code TEXT PRIMARY KEY, description TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_permissions (user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, permission_code TEXT REFERENCES permissions(code) ON DELETE CASCADE, PRIMARY KEY(user_id, permission_code));
CREATE TABLE IF NOT EXISTS audit_logs (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL, resource TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_search_rate_idx ON audit_logs(action, created_at);
CREATE TABLE IF NOT EXISTS user_sessions (session_id TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, bearer_token_hash TEXT UNIQUE, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, email TEXT NOT NULL, ip TEXT NOT NULL, issued_at TIMESTAMPTZ NOT NULL DEFAULT now(), expires_at TIMESTAMPTZ NOT NULL, revoked BOOLEAN NOT NULL DEFAULT false);
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS bearer_token_hash TEXT UNIQUE;
CREATE INDEX IF NOT EXISTS user_sessions_lookup_idx ON user_sessions(token_hash, ip, email, expires_at);
CREATE TABLE IF NOT EXISTS email_verification_tokens (token_hash TEXT PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS password_reset_tokens (token_hash TEXT PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS password_reset_tokens_user_idx ON password_reset_tokens(user_id, expires_at);
CREATE TABLE IF NOT EXISTS smtp_profiles (id TEXT PRIMARY KEY, host TEXT NOT NULL, port INT NOT NULL DEFAULT 587, username TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT true, secret_env TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS smtp_outbox (id BIGSERIAL PRIMARY KEY, smtp_id TEXT REFERENCES smtp_profiles(id) ON DELETE CASCADE, recipient TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS instance_branding (id BOOLEAN PRIMARY KEY DEFAULT true CHECK (id), name TEXT NOT NULL, logo_url TEXT NOT NULL DEFAULT '', website_url TEXT NOT NULL DEFAULT '');
ALTER TABLE instance_branding ADD COLUMN IF NOT EXISTS search_url TEXT NOT NULL DEFAULT '';
ALTER TABLE instance_branding ADD COLUMN IF NOT EXISTS ia_url TEXT NOT NULL DEFAULT '';
ALTER TABLE instance_branding ADD COLUMN IF NOT EXISTS login_url TEXT NOT NULL DEFAULT '';
ALTER TABLE instance_branding ADD COLUMN IF NOT EXISTS register_url TEXT NOT NULL DEFAULT '';
ALTER TABLE instance_branding ADD COLUMN IF NOT EXISTS account_url TEXT NOT NULL DEFAULT '';
ALTER TABLE instance_branding ADD COLUMN IF NOT EXISTS api_url TEXT NOT NULL DEFAULT '';
INSERT INTO instance_branding(id,name) VALUES (true,'NolCore') ON CONFLICT (id) DO NOTHING;
INSERT INTO permissions(code,description) VALUES ('users.read','Lire les utilisateurs'),('users.manage','Gérer les utilisateurs'),('admin.read','Accéder à l’administration'),('documents.write','Créer des documents'),('ai.use','Utiliser l’interface IA') ON CONFLICT DO NOTHING;
